# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0002_bord_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='bord',
            name='embed_code',
            field=models.TextField(null=True),
        ),
    ]
